import { connection } from './database'

try {
  await connection.execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE cuties (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR2(255) NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
          NULL; -- table already exists
        ELSE
          RAISE;
        END IF;
    END;
  `)

  console.log('Table created or already exists.')
}
catch (err) {
  console.error('Error creating table:', err)
}
